name: Scrape M3U8 URLs

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: 'The URL to scrape'
        required: true
        default: 'https://example.com'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python scrape_m3u8.py ${{ github.event.inputs.target_url }}
 
